### ISSUE TITLE
[UX] field name not required for classification store intepreter

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/DataDefinitions#131]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Branch?          | master

When I assign a field from the classification store, it's called `classificationstore-MyFeature-17-2`, but I still need to supply `Field name: MyFeature`. This is superfluous and can even reveal bugs such as #130  when not supplied by the user.

Since the field name is known at map time, specifying it again in config should be dropped.

**Comment by dpfaffenbauer** [comment]
true, I will look at it.
