### ISSUE TITLE
[Bug] Support uncountable iterators

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/DataDefinitions#166]
Currently, the importer assumes the provider is always countable which is not the case for iterators and especially generators.

A quick bugfix was done in #162, but it needs to be expanded upon to cover having the progress bar be shown during the process in CLI and Process manager.

> We can move that (with this bugfix) into a separate PR where it's fully fixed, supporting uncountable providers.

_Originally posted by @dkarlovi in https://github.com/w-vision/ImportDefinitions/pull/162/review_comment/create_

**Comment by dkarlovi** [comment]
@dpfaffenbauer we can continue the conversation here.

**Comment by dpfaffenbauer** [comment]
possible now
