### ISSUE TITLE
[Import] log error conditions from interpreters

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/DataDefinitions#181]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Interpreters are specifically linked to columns, they're not invoked on arbitrary data. This means having a data / interpreter mismatch is a configuration / data mistake and should be fixed in some way. You can only fix it if you know about it.

Currently, interpreters will often just do nothing in this case, but in practice, it causes complex misunderstandings with people using the system, people creating the import definitions, people creating the data input, etc.

For example, `AssetUrlInterpreter` behaves basically like this:

```php
if (filter_var($value, FILTER_VALIDATE_URL)) {
    // process
} else {
    // do nothing
}
```

The `do nothing` part is problematic, you don't know it will just skip some input and are left wondering why it did that, but only if you realize it by looking at the data in the system.

Overall, we should look into raising the volume and value of error message significantly. This could be an epic with subtasks listing all the places this needs to improve.

WDYT?

**Comment by dpfaffenbauer** [comment]
I do like the idea as currently it is quite complex analysing why things fail or don't work expected. Do you have a solution in mind?

**Comment by dkarlovi** [comment]
We could start by just logging it.

We start by:
1. listing all the places where adding logging for error conditions makes sense (all the interpreters which skip stuff, for example)
2. injecting a logger into those and logging the error condition
3. adding enough context to make the log entry possible to decipher in reverse

For example, things we need for 3. are:
1. **import definition name** used
2. **filepath** used (1. and 2. make it easier to reproduce/debug)
3. **position** in the input file (row number in row-oriented files, line number in XML for example)
4. **column name** that we're currently processing (property name, etc)
5. **interpreter name** which produced the error
6. **exact value** the interpreter received (makes it easier to Ctrl-F and think about causes)
7. **precise error message** which should explain what went wrong and suggest what to do

For example, imagine this error message:

```
AssetUrlInterpreter expects an URL to process, "/foo/bar/bat" does not look like an URL, will not add an asset to property "manual":
import_definition: products_csv
filepath: /app/var/products.csv
line: 231
column: manual
interpreter: asset_url_interpreter
value: string(12) "/foo/bar/bat"
```
