### ISSUE TITLE
Add new Runnerinterface to change data(-structure)

### ISSUE THREAD

**Issue by ClemensAn** [w-vision/DataDefinitions#188]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Problem: Many Rest-Apis need a certain (often nested) json-structure. It is unnecessary that one has to do that afterwards row per row, instead of just changing the data on the fly. 

This is just a example, i also did some other changes inside this runner function.

I called it exportPreSave, but i guess this name is not exactly a speaking one...
<img width="331" alt="exportPreSave" src="https://user-images.githubusercontent.com/17127701/59746093-67fde700-9276-11e9-844f-3bde8099c52d.png">

**Comment by dpfaffenbauer** [comment]
If you already did some changes, why not create a Pull Request and show me what you did?

**Comment by ClemensAn** [comment]
It was just a quick fix and i figured that you would prefer some other wording.
But i will just redo my stuff and make a pull request

**Comment by dpfaffenbauer** [comment]
we can discuss wording on the PR as well ;)

**Comment by dpfaffenbauer** [comment]
closed due to inactivity on the PR
