### ISSUE TITLE
[Import] Cannot persist mapping configuration

### ISSUE THREAD

**Issue by bramstroker** [w-vision/DataDefinitions#206]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

With the latest master branch persisting the mapping configuration does not work anymore.

Reproduce:
- Go to "Import Definitions"
- "mapping" tab.
- Define a column mapping
- Click "save"

Expected:
GUI is reloaded and my mapping configuration changes are reflected in the GUI

Actual:
All mapping configuration is empty.

Pimcore version: 6.0.2

I have checked the POST data in network inspector and the mapping data is correct there.
After `$form->handleRequest($request)` in the controller the mapping data is lost.

**Comment by dpfaffenbauer** [comment]
fixed

**Comment by Robert-Jankiewicz-weg** [comment]
Hello @dpfaffenbauer, I am facing a similar issue - do you remember which PR resolved this?

**Comment by dpfaffenbauer** [comment]
@Robert-Jankiewicz-weg sorry, this was 6 years ago, I cant remember :D
