### ISSUE TITLE
Are the installation instructions in the README correct?

### ISSUE THREAD

**Issue by wvervuurt** [w-vision/DataDefinitions#219]
| Q                | A
| ---------------- | -----
| Bug report?      | yes (?)
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

When I run the command `composer require w-vision/data-definitions^3.0` I get the following error:

```
[InvalidArgumentException]
  Could not find a matching version of package w-vision/data-definitions^3.0. 
  Check the package spelling, your version constraint and that the package
  is available in a stability which matches your minimum-stability (stable).
```

Is the README not up to date or is this due to some conflict with the other constraints in my repository?

I'm running a standard PimCore 6.1.1 installation under PHP 7.3, I would expect it to work.

Relevant part of my composer.json:
```
  "require": {
    "php": ">=7.2",
    "wikimedia/composer-merge-plugin": "^1.4",
    "pimcore/pimcore": "~6.1.0"
  },
  "require-dev": {
    "cache/integration-tests": "^0.16.0",
    "codeception/codeception": "~2.4.5",
    "laravel/homestead": "^8.5"
  },
```

**Comment by dpfaffenbauer** [comment]
yep, there is an issue in the readme, should be:

`composer require w-vision/data-definitions:^3.0`

colon missing before the version constraint, try it like this pls

**Comment by wvervuurt** [comment]
I feel like I should have been able to spot that 🙈
Seems to work fine now, thank you!
