### ISSUE TITLE
How to use Object Brick Setter 

### ISSUE THREAD

**Issue by chaimkc** [w-vision/DataDefinitions#220]
I am using Import Definitions to try and modify fields on my products and many of those fields are within object bricks. 
In the image below, I have an import file that has an 'ABV Color' column and I want to map that to the 'abv_Color' field within the object brick. The issue is that when mapping the fields, I set the Setter to objectbrick but I can't figure out what value to add to the 'Field' field. I've tried the column names, the ids, and everything else I could come up with but nothing seems to work. 
Can someone help me with this?

![PimCore ObjectBrick Setter](https://user-images.githubusercontent.com/54283307/63289519-57c1b280-c28d-11e9-96f7-9571c15e4118.png)

**Comment by dpfaffenbauer** [comment]
that's is meant to be the mapping field. But: I don't recommend using it, better create custom interpreters to solve that issue.

**Comment by dpfaffenbauer** [comment]
no sorry, I was wrong, actually you have to enter the field name for the brick.

So for example, if you have a brick field called "attributes", you have the enter "attributes" into the setter config

**Comment by dpfaffenbauer** [comment]
Yep, use interpreters ;)
