### ISSUE TITLE
[Providers] Rewrite Providers to use Iterators

### ISSUE THREAD

**Issue by kubaplas** [w-vision/DataDefinitions#226]
We should leverage the possibility to use Iterators as a return of getData in Providers.
This would lower the memory consumption and speed up the import.
Currently, large datasets can even exhaust system memory.
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Branch?          | master

**Comment by dpfaffenbauer** [comment]
possible now, just recently did that.
