### ISSUE TITLE
Doc change

### ISSUE THREAD

**Issue by bananajoe** [w-vision/DataDefinitions#228]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Docs for Interpreters have a wrong class for the standard NoConfiguration-Form. (additional "/Interpreter")
Just that the next peasant doesn't have to figure out why this class could not be loaded...

**Comment by dpfaffenbauer** [comment]
PR?
