### ISSUE TITLE
Not working in Pimcore 6.6.0

### ISSUE THREAD

**Issue by Hbitvof** [w-vision/DataDefinitions#252]
Right after installing with composer require w-vision/data-definitions:^3.0 server error 500.

**Comment by dpfaffenbauer** [comment]
A bit more information would help. I am using this in every pimcore installation I have, and that includes 6.60 as well and it works for me

**Comment by Hbitvof** [comment]
Hi, 

Apologies for my short post. I thought it was not working at all because of the requirements of 6.0.

I investigated further and the installation resetted some rights so Pimcore couldn't write to cache anymore. I solved this and everything is working.

This issue can be closed.

**Comment by MarkHaakman** [comment]
How did you solve this exactly @Hbitvof ? I'm having the same problem with resetted rights for writing to cache..
It would be great if you could help me out.

**Comment by Hbitvof** [comment]
@MarkHaakman do you get error 500 after updating Pimcore?

**Comment by MarkHaakman** [comment]
Yes, I fixed it in the mean time with the help of this post: https://talk.pimcore.org/t/cannot-write-to-cache-directory/416/17

Thank you for your quick response anyway!
