### ISSUE TITLE
Importing data that sometimes have a date giving error when importing to textarea

### ISSUE THREAD

**Issue by Hbitvof** [w-vision/DataDefinitions#261]
Hi,

When importing data (in this case a notes column where sometimes there is a date into it) the import is giving an error and isn't importing this into the textarea field:

Catchable Fatal Error: Object of class DateTime could not be converted to string in /var/www/html/pimcore/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:172

It shoudn't convert this into DateTime format, but just use it as string.

**Comment by dpfaffenbauer** [comment]
Excel Provider?

**Comment by Hbitvof** [comment]
yes, that's correct.

**Comment by dpfaffenbauer** [comment]
not a DataDefs bug. Excel has data-types, if the column is a date-type, we get from excel a date-type. you have to take care about data-conversion.
