### ISSUE TITLE
Export Definitions not loading in latest version

### ISSUE THREAD

**Issue by Hbitvof** [w-vision/DataDefinitions#270]
Hi,

The Export Definitions window to configure the export definitions is not loading anymore when updating to the latest version of Pimcore and the import definitions. 

The import definitions window is loading normally, the export definitions is just giving nothing, also no error.

**Comment by Hbitvof** [comment]
Here some additional information about the error I get in the browser:

![image](https://user-images.githubusercontent.com/41229269/92301306-fa190a80-ef62-11ea-8fab-ea9669414dfd.png)

**Comment by Hbitvof** [comment]
Any update on this?

**Comment by dpfaffenbauer** [comment]
sorry, haven't had time yet.

**Comment by Childhome** [comment]
I'm having the same issue:
No route found for "GET /admin/data_definitions/export_definitions/"

**Comment by Hbitvof** [comment]
@dpfaffenbauer do you have some spare time left soon to fix this issue so we can update to the latest version?

**Comment by dpfaffenbauer** [comment]
@Hbitvof nope, sorry.... I am quite busy at the moment

**Comment by dpfaffenbauer** [comment]
fixed with 3.2.1 release
