### ISSUE TITLE
Improvement: Skip first row option on csv file

### ISSUE THREAD

**Issue by Hbitvof** [w-vision/DataDefinitions#276]
Is it possible to add option to skip first row of a csv file?

Now I get an error all the time on the first row or the first row is imported. Most of the times the first row contains header information.

**Comment by dpfaffenbauer** [comment]
the first row is supposed to have the header inside....

**Comment by Hbitvof** [comment]
@dpfaffenbauer I don't understand you answer. This first row is picked up by Data Definitions to import and giving errors:

![image](https://user-images.githubusercontent.com/41229269/96453895-656d2200-121b-11eb-9ca1-3cae799e28a0.png)

In this case the error is normal because it wants to import the name of a field into a numeric value. But it shouldn't do anything with this header.

**Comment by dpfaffenbauer** [comment]
A CSV file is supposed to have a header in row "0". My CSV Imports always have a header and it doesn't get imported...

**Comment by Hbitvof** [comment]
This is also a normal csv file with header:

![image](https://user-images.githubusercontent.com/41229269/96454423-1ecbf780-121c-11eb-8867-149c590869b8.png)

Nothing special about it. I see this behavior on all csv files I import with Import Definitions.

**Comment by dpfaffenbauer** [comment]
it might depend on the configuration you use, if you use the "headers" config, it doesn't skip the first row, if you use the "example" config, it skips the first row

**Comment by aarongerig** [comment]
@Hbitvof Have you filled in the CSV Example setting?
![csv_settings](https://user-images.githubusercontent.com/17384333/96454802-aca7e280-121c-11eb-9907-8f9ee50653d9.png)

**Comment by Hbitvof** [comment]
Ah, I filled in the CSV headers, not the CSV example. I changed an import ran again and the errors are gone.

Completely my bad, apologies taking your time.
