### ISSUE TITLE
Trying to create a new linked object with sub-definitions. 

### ISSUE THREAD

**Issue by Timonwatteny** [w-vision/DataDefinitions#281]
Hello 

I am trying to run a sub-definition while importing products. If the brand already exists, the object needs to be linked, otherwise create the object and link it. 

I've create a sub-definition that accepts a raw format to create the brand, everything is going fine but I don't manage to create the product in the same import (sub-definition is created). The object I created can't be resolved in any way. In my main import (that I am running) I map the field to the a sub-definition with the nested interpreter, then I tried an object-resolver, href, everything that has to do with objects. 

ERROR MESSAGE: ERROR     [import_definition] Error: Call to a member function getType() on array in /phpapp/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/ManyToOneRelation.php:724

Is it possible to give some tips what I need to do to make this work? I tried consulting the code + documentation but I didn't manage to make it happen yet.

**Comment by Timonwatteny** [comment]
It is going wrong when I add the relation as a setter by the way.

**Comment by Timonwatteny** [comment]
I've just noticed I don't need to add a setter if I run a sub-definition to create the relation. Does that make sense?

**Comment by aarongerig** [comment]
Hi @Timonwatteny,

Yes, that totally does make sense. [Setters](https://github.com/w-vision/DataDefinitions/blob/master/docs/import/setter.md) are only used for setting data to special fields, which require the data to be in a certain format (e.g. Objectbricks, Localizedfields, Classficationstores, Fieldcollections, etc.).
In your case it should be enough to only run the sub-definition via the nested interpreter without setting any setter configuration.

Let me know if it works for you or if you have any question. :)

**Comment by Timonwatteny** [comment]
Well yes but it's not completely clear for me what I add in the provider settings in the sub-definition. I moved the CSV headers to CSV example in the main import because I got a second object created by the headers (which I don't want). And now I am trying with a custom mapping in the sub-definition but that doesn't seem to werk.

**Comment by aarongerig** [comment]
If your CSV contains headers, leave the "CSV Headers" field empty. You should only use it, if your CSV **does not** contain any headers.

<img width="1306" alt="data_definitions_csv_headers" src="https://user-images.githubusercontent.com/17384333/102602136-65a57300-4121-11eb-825a-a9326dfd17e3.png">

**Comment by Timonwatteny** [comment]
Yes @aarongerig  that is exactly what I did now. And since then I can't import my sub-object anymore. Is the sub-definition still in raw format? And what fields do I add in the provider settings?

**Comment by dpfaffenbauer** [comment]
Sub Definition should be in RAW Format, the values you give it, should be an array that corresponds to the RAW value, then you can use the sub-definition to import relations.

**Comment by Timonwatteny** [comment]
And how exactly can I determine how the RAW value looks like then? 

By the way, thanks a lot for the quick responds.

**Comment by dpfaffenbauer** [comment]
Well, Every Import Column works like this:

 - Give it a field from your import source, that is the 'value'
 - Interpreters transform the value in whatever you want
 - For Relations, you usually have one or multiple fields that define it. let's say we have 2 fields for a relation "internal_id" and "name"
 - Use a nested interpreter
 - First: Expression with value: [data['internal_id'], data['name']]
 - Second: Definition and choose your definition

your raw data would be internal_id,name

These two fields are then also available in the sub-def.

**Comment by Timonwatteny** [comment]
I understand what you mean but still the field does not get mapped in the sub-definition for some reason: 
![Screenshot 2020-12-18 at 11 54 41](https://user-images.githubusercontent.com/31765954/102607065-f717e380-4127-11eb-948c-45b40591a9ba.png)
![Screenshot 2020-12-18 at 11 54 32](https://user-images.githubusercontent.com/31765954/102607066-f7b07a00-4127-11eb-8ee2-1729079541f0.png)
![Screenshot 2020-12-18 at 11 54 29](https://user-images.githubusercontent.com/31765954/102607068-f8491080-4127-11eb-8daa-69999c3249b9.png)
![Screenshot 2020-12-18 at 11 54 18](https://user-images.githubusercontent.com/31765954/102607072-f8e1a700-4127-11eb-95d9-ed8efdbbf6fe.png)
![Screenshot 2020-12-18 at 11 54 12](https://user-images.githubusercontent.com/31765954/102607075-f97a3d80-4127-11eb-9b19-29ae4e510b39.png)

**Comment by dpfaffenbauer** [comment]
sorry, I was wrong. It doesn't give the value, it gives the whole row as data to the subdef. so what you define in RAW should actually be one row of your import source

**Comment by Timonwatteny** [comment]
That means that I don't need an expression in my main definition?

**Comment by Timonwatteny** [comment]
The problem I am facing is as follow: If I give all my headers in the CSV headers in my main definition it works, the brand is getting imported from the subdefinition (problem here is I get 2 products and brands because the module sees the csv header as a data row too). If I however give these headers as a CSV example (because they are in my csv) it doesn't work anymore. At the moment I am giving all my csv headers in the sub-definition as well.

**Comment by dpfaffenbauer** [comment]
yes, but that seems to be a different issue, the sub definition works
