### ISSUE TITLE
Ability to invoke the definition by name

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/DataDefinitions#290]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

```
bin/console data:export -d "Products"
```

is more clear than:

```
bin/console data:export -d 12
```

We could even add a `title` field to definitions which could then be more elaborate (for human consumption), but `name` is used for this lookup.

**Comment by dpfaffenbauer** [comment]
that already works....

`bin/console da:ex -d NameOfDefinition`

**Comment by dkarlovi** [comment]
Huh, it didn't work for me, maybe I had a typo. :thinking: Thanks! :100:
