### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by p380** [w-vision/DataDefinitions#296]
report an error after installation
Defined Kernel Class \AppKernel not found

**Comment by dpfaffenbauer** [comment]
doesn't help, any more information?

**Comment by p380** [comment]
i installed via composer with command
composer require w-vision / data-definitions: ^ 3.0

an error occurs when I refresh the page

**Comment by p380** [comment]
I solved that.
I manually copied the folder from the ‘src’ and it works.

**Comment by Notebit** [comment]
I had the same problem and now I am not even able to login into administration cause I get 

> You have requested a non-existent parameter "kernel.secret".

Which folder you copied and where?

**Comment by msramanujam** [comment]
@dpfaffenbauer - Could use some help here friend. I just tried installing the bundle & when I tried to enable the bundle, after a series of successful changes, the system throws the following error. Now, the admin console wouldn't load either & throws the same error:

`Running post state change commands
----------------------------------

 // Running bin/console assets:install...                                                                               


Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.secret')
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('kernel.secret')
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%kernel.secret%', Array)
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Co in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100

 // Running bin/console cache:clear...                                                                                  


Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.secret')
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('kernel.secret')
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%kernel.secret%', Array)
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Co in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
root@6b939ab3ef76:/var/www/html# bin/console pimcore:bundle:install DataDefinitionsBundle

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.secret')
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('kernel.secret')
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%kernel.secret%', Array)
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Co in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
`

**Comment by msramanujam** [comment]
I just went ahead & added the missing parameter to the parameters.yml & the issue went away. I'm sure just adding a parameter there isn't probably a good idea since I haven't put a good value there for the parameter. But, for now, the other things work.

**Comment by msramanujam** [comment]
> @dpfaffenbauer - Could use some help here friend. I just tried installing the bundle & when I tried to enable the bundle, after a series of successful changes, the system throws the following error. Now, the admin console wouldn't load either & throws the same error:
> 
> ## `Running post state change commands
> // Running bin/console assets:install...
> 
> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
> Stack trace:
> #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.secret')
> #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('kernel.secret')
> #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%kernel.secret%', Array)
> #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Co in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
> 
> // Running bin/console cache:clear...
> 
> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
> Stack trace:
> #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.secret')
> #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('kernel.secret')
> #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%kernel.secret%', Array)
> #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Co in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
> root@6b939ab3ef76:/var/www/html# bin/console pimcore:bundle:install DataDefinitionsBundle
> 
> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
> Stack trace:
> #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('kernel.secret')
> #1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(216): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('kernel.secret')
> #2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(187): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%kernel.secret%', Array)
> #3 /var/www/html/vendor/symfony/symfony/src/Symfony/Co in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
> `

I just went ahead & added the missing parameter to the parameters.yml & the issue went away. I'm sure just adding a parameter there isn't probably a good idea since I haven't put a good value there for the parameter. But, for now, the other things work.

**Comment by dpfaffenbauer** [comment]
That is a default symfony parameter. Not sure what you did but that is not a data defs problem
