### ISSUE TITLE
Not working with Pimcore 10.0.*@beta

### ISSUE THREAD

**Issue by shaselboeck** [w-vision/DataDefinitions#306]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

DataDefinitions is not working with Pimcore 10.0.*@beta. It would be great if it is compatible so that I can test before the Pimcore release. In addition, the built-in CSV import from Pimcore has been removed. There is no alternative to importing data for customers.

**Comment by dpfaffenbauer** [comment]
I don't think this will happen before the release. I have to release CoreShop first in order to release this... I'll close this ticket for now since it is obvious that DataDefs should support Pimcore X

**Comment by ITspirit** [comment]
Is there anything where i can support you?
Sure, DataDef rely a lot to CoreShop, so CoreShop should be ready first. 
Any Time-Roadmap from your site Dominik?

**Comment by ITspirit** [comment]
#308
