### ISSUE TITLE
Error: Interpreter assets_url does not update existing objects

### ISSUE THREAD

**Issue by Jimerson21** [w-vision/DataDefinitions#326]
Hello, 

"w-vision/data-definitions": "dev-master"
"pimcore/pimcore": "^10.1.0"

The following error is related to the assets_url interpreter, it is not possible to update an existing asset, the following error occurs:

![image](https://user-images.githubusercontent.com/58362749/131355630-a9f7e6df-795a-4a1d-86cb-6053d79a98d3.png)

![image](https://user-images.githubusercontent.com/58362749/131356263-a577c061-4367-4270-b9bc-fe296f8e3b28.png)

As a solution I propose to modify the sentence as follows:

     $select->join('assets','assets_metadata', 'am', 'id = am.cid');

**Comment by dkarlovi** [comment]
@Jimerson21 the join clause must have changed with Pimcore X. Mind to create a PR?

**Comment by dkarlovi** [comment]
The fix given here is good, we need to implement it.
