### ISSUE TITLE
Composer conflict dependencies with pimcore 10.x

### ISSUE THREAD

**Issue by savosik** [w-vision/DataDefinitions#327]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? |no
| BC Break report? |no
| RFC?             | no
| Branch?          | master

Hello, guys

When I run  this `composer require w-vision/data-definitions` command, I have that exception

 Problem 1
    - w-vision/data-definitions[3.2.0, ..., 3.2.7] require pimcore/pimcore ^6.5 -> found pimcore/pimcore[v6.5.0, ..., v6.9.6] but                          it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires w-vision/data-definitions ^3.2 -> satisfiable by w-vision/data-definitions[3.2.0, ..., 3.2.7].

How can I solve it?

**Comment by dpfaffenbauer** [comment]
try with `composer require w-vision/data-definitions:dev-master`

or adding these into your composer.json

```
"minimum-stability": "dev",
"prefer-stable": true
```
