### ISSUE TITLE
Pimcore X compatiblity ?

### ISSUE THREAD

**Issue by brainsbucket** [w-vision/DataDefinitions#334]
Hi,
thanks for your great job with this extension !

Is it possible to know when DataDefinition will be compatible with Pimcore X ?

**Comment by aarongerig** [comment]
Hi @brainsbucket ,

Actually, DataDefinitions is already compatible with Pimcore X. For now you have to require the `dev-master` version in your composer.json file:

```json
{
  ...
  "require": {
    "w-vision/data-definitions": "dev-master"
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}
```

As soon as [CoreShop](https://github.com/coreshop/CoreShop) will released its stable `v3.0.0`, then DataDefinition will release its stable `v4.0.0`.
