### ISSUE TITLE
Unable to install in PimCore X

### ISSUE THREAD

**Issue by Hbitvof** [w-vision/DataDefinitions#354]
How to install 4.x? When following instructions Composer wants to install 3.x with errors.

**Comment by aarongerig** [comment]
Hi @Hbitvof 
Make sure you have the following settings in your `composer.json` when requiring the v4 of DataDefinitions.

```json
{
    ...
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by Hbitvof** [comment]
I did but still not working.

Can you please update the instruction to install this in PimCore X? There is no single information about this and I guess I am not the only one that can't figure this out.
