### ISSUE TITLE
Export Many-To-Many Relation by Name not by Path

### ISSUE THREAD

**Issue by Nesfiran** [w-vision/DataDefinitions#355]
Hello all,
I'm trying to export several categories, which works so far but the format doesn't suit me. The system always exports the categories with the CoreShop path.
But I only want to have the name of the category without the path so that I can search for it during the import via ObjectResolver.

Can anyone give me a tip on how to achieve this?
I use the **expression** with the following code for the current output.

`implode('|', value)`

Result: `/coreshop/categories/category1`
Target: `category1`

Greetings

**Comment by dpfaffenbauer** [comment]
use expressions combined with iterator
