### ISSUE TITLE
Import/Export GC running too infrequently

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/DataDefinitions#368]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

Currently the exporter will run GC every 1000 rows exported:
https://github.com/w-vision/DataDefinitions/blob/876d7d2aa05c0b7b0a7dd35eaea96af375805f7a/src/DataDefinitionsBundle/Exporter/Exporter.php#L137

But this is way too infrequent because rows can be really heavy and need GC way before that. I see no reason why we wouldn't just run GC after every loop (which is currently at 50 items). @dpfaffenbauer?

**Comment by dkarlovi** [comment]
Same for the importer:
https://github.com/w-vision/DataDefinitions/blob/876d7d2aa05c0b7b0a7dd35eaea96af375805f7a/src/DataDefinitionsBundle/Importer/Importer.php#L261

**Comment by dpfaffenbauer** [comment]
👍
