### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by dpfaffenbauer** [w-vision/DataDefinitions#420]
Dear Contributors, we are planning to make this plugin dual licensed (under GPLv3 and MIT) to be compatible with Pimcore Enterprise and Professional. In Order to do that, we need your approval (basically a contributor license agreement). The agreement can be found here: https://github.com/instride-ch/pimcore-data-definitions/blob/5.0/CLA.md

Can the following contributors please sign it by writing 

"I have read the CLA Document and I hereby sign the CLA"

into this Issue as comment?

 - [x] @dkarlovi 
 - [x] @blankse
 - [x] @roynilsson 
 - [x] @ivanmerta
 - [x] @wpeisert
 - [x] @bramstroker 
 - [x] @MiragePresent 
 - [x] @kkirsz 
 - [x] @prugala 
 - [x] @kubaplas 
 - [x] @slri 
 - [x] @t-zilla 
 - [x] @ramundomario 
 - [x] @damijank 
 - [x] @dolmit-tanel-paaro 
 - [x] @mbolka 
 - [x] @tip-top-b 
 - [ ] @josh-palan 
 - [x] @sigere 
 - [x] @aclDeveloper 
 - [x] @ITspirit 
 - [x] @brainsbucket 
 - [x] @marekgach 
 - [x] @michalfilik 
 - [x] @mischief24 
 - [x] @zavodyanka 
 - [x] @fffab 
 - [x] @solverat 
 - [x] @Cruiser13

**Comment by marekgach** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tip-top-b** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
thanks guys

**Comment by Cruiser13** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mbolka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by michalfilik** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by solverat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kkirsz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by prugala** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by blankse** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ramundomario** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by damijank** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dolmit-tanel-paaro** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ITspirit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MiragePresent** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bramstroker** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by t-zilla** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
ping @dkarlovi @roynilsson @ivanmerta @wpeisert @kubaplas @siri @josh-palan @sigere @aclDeveloper @brainsbucket @mischief24 @zavodyanka @fffab

**Comment by dkarlovi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ivanmerta** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
ping @roynilsson, @wpeisert, @kubaplas, @slri, @josh-palan, @sigere, @aclDeveloper,  @mischief24, @zavodyanka, @fffab

could you be so good please? :)

**Comment by slri** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fffab** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by roynilsson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sigere** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mischief24** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aclDeveloper** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
@brainsbucket lost access to the account, he gave consent via linked in messenger:

<img width="1351" alt="Screenshot 2024-09-27 at 09 51 35" src="https://github.com/user-attachments/assets/8f9e5dff-c70d-4bcd-83ee-ccb374b2c0d8">

<img width="473" alt="Screenshot 2024-09-27 at 09 51 20" src="https://github.com/user-attachments/assets/379c579c-1be7-4f68-a3f7-9ad41c83e50a">

**Comment by dpfaffenbauer** [comment]
I tried to contact @zavodyanka on LinkedIn, but she misunderstood the message and deleted it. So no consent from here.

**Comment by kubaplas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
Im can't reach @josh-palan, but his contributions were super small, so I'd say they don't count as a copyright infringement if we change the license.

**Comment by zavodyanka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wpeisert** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
We will change the license. We can't reach @josh-palan in any way possible....
